### ISSUE TITLE
Reaction Wheels for attitude control

### ISSUE THREAD

**Issue by eberkain** [linuxgurugamer/RCSBuildAid#10]
It would be great if there was a mode that showed me a torque circle that represented how strong the reaction wheels were on the vessel.

**Comment by linuxgurugamer** [comment]
The original author has taken it over again, you need to direct your comments to him.

**Comment by eberkain** [comment]
then you should probably take your version off CKAN?

**Comment by linuxgurugamer** [comment]
I'll let him know to get it updated.  My version works, just not moving forward with it

**Comment by linuxgurugamer** [comment]
One final comment:  On CKAN, the highest level for my version is 1.8.
