### ISSUE TITLE
Sorry, Linux, what version do I use for KSP 1.2.2? 

### ISSUE THREAD

**Issue by mark-c** [linuxgurugamer/RCSBuildAid#6]
I tried downloading the October 2016 one, but it only gave me a source, apparently. And I have no C#, etc. to make it.

What release can I use--is there one?

Thank you.

**Comment by krisavi** [comment]
You can check at curse
https://www.curseforge.com/kerbal/ksp-mods/rcs-build-aid/files

edit: curse changed structure, new link:
https://kerbal.curseforge.com/projects/rcs-build-aid/files

**Comment by mark-c** [comment]
Edit:  Hey Mr. Avi, this is what the files look like:  https://i.imgur.com/gNJsbRu.png

Can I use it like that? Thanks a lot. Sorry for the trouble.

MC

**Comment by krisavi** [comment]
Hey, I believe the files should be ok, you don't even need Sources folder there

I have not tested it, so I can't be sure.

There is also README.ascii that describes what you might need. (You just need to open it with text editor like notepad)
