### ISSUE TITLE
KSP 1.8 Support?

### ISSUE THREAD

**Issue by cculianu** [linuxgurugamer/RCSBuildAid#9]
Are there any intentions on updating this mod for 1.8? I really love this module. Please let me know!

**Comment by linuxgurugamer** [comment]
The more you ask, the longer it will take

**Comment by cculianu** [comment]
Man, I didn't mean it as passive or active aggression. Don't take it that way.  I'm also a developer and I have like 13 projects going on and I can relate to people asking you to do stuff for free. 

No worries. 

Just know your mods and contribution to KSP are awesome and you are appreciated.  You have singlehandedly picked up the slack on so many quality mods and made them better. Kudos to you.

**Comment by linuxgurugamer** [comment]
Sorry. It just seemed that people are starting to post those messages on Github instead of the forums.
I have 200 mods to update, have done about 20 so far

**Comment by cculianu** [comment]
Godspeed my friend. :)
